### ISSUE TITLE
Links to be used in the last letter to the speakers

### ISSUE THREAD

**Issue by MagnusTim** [Swetugg/swetugg-backoffice#189]
Hej,

Vad har dessa länkar för motsvarighet i gbg-2023, att bara byta sthlm mot gbg fungerade inte.

https://www.swetugg.se/sthlm-2023/code-of-conduct
https://www.swetugg.se/sthlm-2023#schedule
https://swetugg.se/sthlm-2023/logos

**Comment by ceciliasharp** [comment]
issue resolved
